# Generated by Django 4.2.9 on 2026-03-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('requirements', models.TextField(help_text='如：Python, Django, MySQL, 3年经验', verbose_name='职位要求（关键词，用逗号分隔）')),
                ('description', models.TextField(blank=True, default='', verbose_name='职位描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='学历')),
                ('skills', models.TextField(blank=True, help_text='自动从简历中提取的技能', verbose_name='技能')),
                ('raw_text', models.TextField(blank=True, verbose_name='简历原始文本')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历文件')),
                ('score', models.FloatField(default=0.0, verbose_name='匹配分数')),
                ('status', models.CharField(choices=[('pending', '待筛选'), ('passed', '通过'), ('rejected', '淘汰')], default='pending', max_length=20, verbose_name='状态')),
                ('matched_keywords', models.TextField(blank=True, help_text='JSON格式', verbose_name='匹配的关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resumes.jobposition')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-score'],
            },
        ),
    ]
